export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-lg shadow-md p-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">GoServePH Data Privacy Policy</h1>
          <p className="text-lg text-gray-600 mb-8">
            Protecting the information you and your users handle through our system is our highest priority. This policy outlines how GoServePH manages, secures, and uses your data.
          </p>
          
          <div className="prose prose-gray max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">1. How We Define and Use Data</h2>
              <p className="text-gray-700 mb-4">In this policy, we define the types of data that flow through the GoServePH system:</p>
              
              <table className="min-w-full border border-gray-300 mb-6">
                <thead className="bg-gray-100">
                  <tr>
                    <th className="border border-gray-300 px-4 py-2 text-left">Term</th>
                    <th className="border border-gray-300 px-4 py-2 text-left">Definition</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 font-semibold">Personal Data</td>
                    <td className="border border-gray-300 px-4 py-2">Any information that can identify a specific person, whether directly or indirectly, shared or accessible through the Services.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 font-semibold">User Data</td>
                    <td className="border border-gray-300 px-4 py-2">Information that describes your business operations, services, or internal activities.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 font-semibold">GoServePH Data</td>
                    <td className="border border-gray-300 px-4 py-2">Details about transactions and activity on our platform, information used for fraud detection, aggregated data, and any non-personal information generated by our system.</td>
                  </tr>
                  <tr>
                    <td className="border border-gray-300 px-4 py-2 font-semibold">DATA</td>
                    <td className="border border-gray-300 px-4 py-2">Used broadly to refer to all the above: Personal Data, User Data, and GoServePH Data.</td>
                  </tr>
                </tbody>
              </table>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Our Commitment to Data Use</h3>
              <p className="text-gray-700 mb-3">We analyze and manage data only for the following critical purposes:</p>
              <ul className="list-disc pl-6 mb-4 text-gray-700">
                <li>To provide, maintain, and improve the GoServePH Services for you and all other users.</li>
                <li>To detect and mitigate fraud, financial loss, or other harm to you or other users.</li>
                <li>To develop and enhance our products, systems, and tools.</li>
              </ul>
              <p className="text-gray-700 mb-6">
                We will not sell or share Personal Data with unaffiliated parties for their marketing purposes. By using our system, you consent to our use of your Data in this manner.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Data Protection and Compliance</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Confidentiality</h3>
              <p className="text-gray-700 mb-4">
                We commit to using Data only as permitted by our agreement or as specifically directed by you. You, in turn, must protect all Data you access through GoServePH and use it only in connection with our Services. Neither party may use Personal Data to market to third parties without explicit consent.
              </p>
              <p className="text-gray-700 mb-6">
                We will only disclose Data when legally required to do so, such as through a subpoena, court order, or search warrant.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Privacy Compliance and Responsibilities</h3>
              <p className="text-gray-700 mb-3"><strong>Your Legal Duty:</strong> You affirm that you are, and will remain, compliant with all applicable Philippine laws (including the Data Privacy Act of 2012) governing the collection, protection, and use of the Data you provide to us.</p>
              
              <p className="text-gray-700 mb-3"><strong>Consent:</strong> You are responsible for obtaining all necessary rights and consents from your End-Users to allow us to collect, use, and store their Personal Data.</p>
              
              <p className="text-gray-700 mb-6"><strong>End-User Disclosure:</strong> You must clearly inform your End-Users that GoServePH processes transactions for you and may receive their Personal Data as part of that process.</p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Data Processing Roles</h3>
              <p className="text-gray-700 mb-3">When we process Personal Data on your behalf, we operate under the following legal roles:</p>
              <ul className="list-disc pl-6 mb-4 text-gray-700">
                <li>You are the <strong>Data Controller</strong> (you determine why and how the data is processed).</li>
                <li>We are the <strong>Data Intermediary</strong> (we process data strictly according to your instructions).</li>
              </ul>
              
              <p className="text-gray-700 mb-3">As the Data Intermediary, we commit to:</p>
              <ul className="list-disc pl-6 mb-4 text-gray-700">
                <li>Implementing appropriate security measures to protect the Personal Data we process.</li>
                <li>Not retaining Personal Data longer than necessary to fulfill the purposes set out in our agreement.</li>
              </ul>
              
              <p className="text-gray-700 mb-6">
                You acknowledge that we rely entirely on your instructions. Therefore, we are not liable for any claims resulting from our actions that were based directly or indirectly on your instructions.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Prohibited Activities</h3>
              <p className="text-gray-700 mb-6">
                You are strictly prohibited from data mining the GoServePH database or any portion of it without our express written permission.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Breach Notification</h3>
              <p className="text-gray-700 mb-6">
                If we become aware of an unauthorized acquisition, disclosure, change, or loss of Personal Data on our systems (a "Breach"), we will notify you and provide sufficient information to help you mitigate any negative impact, consistent with our legal obligations.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Account Deactivation and Data Deletion</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Initiating Deactivation</h3>
              <p className="text-gray-700 mb-6">
                If you wish to remove your personal information from our systems, you must go to your Edit Profile page and click the 'Deactivate Account' button. This action initiates the data deletion and account deactivation process.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Data Retention</h3>
              <p className="text-gray-700 mb-4">
                Upon deactivation, all of your Personal Identifying Information will be deleted from our systems.
              </p>
              <p className="text-gray-700 mb-6">
                <strong>Important Note:</strong> Due to the nature of our role as a Government Services Management System, and for legal, accounting, and audit purposes, we are required to retain some of your non-personal account activity history and transactional records. You will receive a confirmation email once your request has been fully processed.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Security Controls and Responsibilities</h2>
              
              <h3 className="text-xl font-semibold text-gray-900 mb-3">Our Security</h3>
              <p className="text-gray-700 mb-6">
                We are responsible for implementing commercially reasonable administrative, technical, and physical procedures to protect Data from unauthorized access, loss, or modification. We comply with all applicable Laws in handling Data.
              </p>

              <h3 className="text-xl font-semibold text-gray-900 mb-3">Your Security Controls</h3>
              <p className="text-gray-700 mb-3">
                You acknowledge that no security system is perfect. You agree to implement your own necessary security measures ("Security Controls"), which must include:
              </p>
              <ul className="list-disc pl-6 mb-4 text-gray-700">
                <li>Firewall and anti-virus systems.</li>
                <li>Anti-phishing systems.</li>
                <li>End-User and device management policies.</li>
                <li>Data handling protocols.</li>
              </ul>
              <p className="text-gray-700 mb-6">
                We reserve the right to suspend your Account or the Services if necessary to maintain system integrity and security, or to prevent harm. You waive any right to claim losses that result from a Breach or any action we take to prevent harm.
              </p>
            </section>
          </div>

          <div className="mt-8 pt-6 border-t border-gray-200">
            <a href="/services" className="text-green-600 hover:text-green-700 font-semibold">
              ← Back to Services
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}
