import { prisma } from "./prisma"

export interface AuditLogData {
  userId: string
  action: string
  entityType: string
  entityId?: string
  details?: Record<string, any>
  ipAddress?: string
  userAgent?: string
}

export async function createAuditLog(data: AuditLogData) {
  try {
    await prisma.auditLog.create({
      data: {
        userId: data.userId,
        action: data.action,
        entityType: data.entityType,
        entityId: data.entityId,
        details: data.details ? JSON.stringify(data.details) : null,
        ipAddress: data.ipAddress,
        userAgent: data.userAgent
      }
    })
  } catch (error) {
    // Log error but don't throw - audit logging shouldn't break main functionality
    console.error("Failed to create audit log:", error)
  }
}

// Audit action constants
export const AUDIT_ACTIONS = {
  // Death Registration
  DEATH_REGISTRATION_SUBMITTED: "DEATH_REGISTRATION_SUBMITTED",
  DEATH_REGISTRATION_APPROVED: "DEATH_REGISTRATION_APPROVED",
  DEATH_REGISTRATION_REJECTED: "DEATH_REGISTRATION_REJECTED",
  DEATH_REGISTRATION_RETURNED: "DEATH_REGISTRATION_RETURNED",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  CERTIFICATE_READY: "CERTIFICATE_READY",
  CERTIFICATE_COMPLETED: "CERTIFICATE_COMPLETED",
  
  // Burial Permit
  BURIAL_PERMIT_SUBMITTED: "BURIAL_PERMIT_SUBMITTED",
  BURIAL_PERMIT_APPROVED: "BURIAL_PERMIT_APPROVED",
  BURIAL_PERMIT_REJECTED: "BURIAL_PERMIT_REJECTED",
  BURIAL_PERMIT_PAYMENT_CONFIRMED: "BURIAL_PERMIT_PAYMENT_CONFIRMED",
  BURIAL_PERMIT_READY: "BURIAL_PERMIT_READY",
  BURIAL_PERMIT_COMPLETED: "BURIAL_PERMIT_COMPLETED",
  
  // Exhumation Permit
  EXHUMATION_PERMIT_SUBMITTED: "EXHUMATION_PERMIT_SUBMITTED",
  EXHUMATION_PERMIT_APPROVED: "EXHUMATION_PERMIT_APPROVED",
  EXHUMATION_PERMIT_REJECTED: "EXHUMATION_PERMIT_REJECTED",
  EXHUMATION_PERMIT_PAYMENT_CONFIRMED: "EXHUMATION_PERMIT_PAYMENT_CONFIRMED",
  EXHUMATION_PERMIT_READY: "EXHUMATION_PERMIT_READY",
  EXHUMATION_PERMIT_COMPLETED: "EXHUMATION_PERMIT_COMPLETED",
  
  // Cremation Permit
  CREMATION_PERMIT_SUBMITTED: "CREMATION_PERMIT_SUBMITTED",
  CREMATION_PERMIT_APPROVED: "CREMATION_PERMIT_APPROVED",
  CREMATION_PERMIT_REJECTED: "CREMATION_PERMIT_REJECTED",
  CREMATION_PERMIT_PAYMENT_SUBMITTED: "CREMATION_PERMIT_PAYMENT_SUBMITTED",
  CREMATION_PERMIT_PAYMENT_CONFIRMED: "CREMATION_PERMIT_PAYMENT_CONFIRMED",
  CREMATION_PERMIT_READY: "CREMATION_PERMIT_READY",
  CREMATION_PERMIT_COMPLETED: "CREMATION_PERMIT_COMPLETED",
  
  // Death Certificate Request
  DEATH_CERTIFICATE_REQUEST_SUBMITTED: "DEATH_CERTIFICATE_REQUEST_SUBMITTED",
  DEATH_CERTIFICATE_REQUEST_APPROVED: "DEATH_CERTIFICATE_REQUEST_APPROVED",
  DEATH_CERTIFICATE_REQUEST_REJECTED: "DEATH_CERTIFICATE_REQUEST_REJECTED",
  DEATH_CERTIFICATE_REQUEST_PAYMENT_SUBMITTED: "DEATH_CERTIFICATE_REQUEST_PAYMENT_SUBMITTED",
  DEATH_CERTIFICATE_REQUEST_PAYMENT_CONFIRMED: "DEATH_CERTIFICATE_REQUEST_PAYMENT_CONFIRMED",
  DEATH_CERTIFICATE_REQUEST_PRINTED: "DEATH_CERTIFICATE_REQUEST_PRINTED",
  DEATH_CERTIFICATE_REQUEST_READY: "DEATH_CERTIFICATE_REQUEST_READY",
  DEATH_CERTIFICATE_REQUEST_COMPLETED: "DEATH_CERTIFICATE_REQUEST_COMPLETED",
  
  // Drainage Request
  DRAINAGE_REQUEST_SUBMITTED: "DRAINAGE_REQUEST_SUBMITTED",
  DRAINAGE_REQUEST_UPDATED: "DRAINAGE_REQUEST_UPDATED",
  DRAINAGE_REQUEST_ASSIGNED: "DRAINAGE_REQUEST_ASSIGNED",
  DRAINAGE_INSPECTION_SCHEDULED: "DRAINAGE_INSPECTION_SCHEDULED",
  DRAINAGE_INSPECTION_COMPLETED: "DRAINAGE_INSPECTION_COMPLETED",
  DRAINAGE_REQUEST_APPROVED: "DRAINAGE_REQUEST_APPROVED",
  DRAINAGE_REQUEST_COMPLETED: "DRAINAGE_REQUEST_COMPLETED",
  DRAINAGE_REQUEST_REJECTED: "DRAINAGE_REQUEST_REJECTED",
  
  // Water Connection
  WATER_CONNECTION_SUBMITTED: "WATER_CONNECTION_SUBMITTED",
  WATER_CONNECTION_UPDATED: "WATER_CONNECTION_UPDATED",
  WATER_CONNECTION_RETURNED: "WATER_CONNECTION_RETURNED",
  WATER_CONNECTION_INSPECTION_SCHEDULED: "WATER_CONNECTION_INSPECTION_SCHEDULED",
  WATER_CONNECTION_BILLING: "WATER_CONNECTION_BILLING",
  WATER_CONNECTION_PAYMENT_CONFIRMED: "WATER_CONNECTION_PAYMENT_CONFIRMED",
  WATER_CONNECTION_INSTALLATION_SCHEDULED: "WATER_CONNECTION_INSTALLATION_SCHEDULED",
  WATER_CONNECTION_ACTIVE: "WATER_CONNECTION_ACTIVE",
  WATER_CONNECTION_REJECTED: "WATER_CONNECTION_REJECTED",
  
  // Water Issue
  WATER_ISSUE_SUBMITTED: "WATER_ISSUE_SUBMITTED",
  WATER_ISSUE_UPDATED: "WATER_ISSUE_UPDATED",
  WATER_ISSUE_ASSIGNED: "WATER_ISSUE_ASSIGNED",
  WATER_ISSUE_INSPECTION_SCHEDULED: "WATER_ISSUE_INSPECTION_SCHEDULED",
  WATER_ISSUE_REPAIR_SCHEDULED: "WATER_ISSUE_REPAIR_SCHEDULED",
  WATER_ISSUE_RESOLVED: "WATER_ISSUE_RESOLVED",
  WATER_ISSUE_CANNOT_REPAIR: "WATER_ISSUE_CANNOT_REPAIR",
  WATER_ISSUE_CLOSED: "WATER_ISSUE_CLOSED",
  
  // User Management
  USER_REGISTERED: "USER_REGISTERED",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_UPDATED: "USER_UPDATED",
  USER_DELETED: "USER_DELETED",
} as const
